services:
 nginx-proxy:
  image: 'jc21/nginx-proxy-manager:latest'
  container_name: nginx-proxy
  restart: always
  ports:
   - '80:80'
   - '81:81'
   - '443:443'

 db:
  image: mysql:latest
  container_name: mysql
  depends_on:
   - nginx-proxy
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: admin_password
   MYSQL_DATABASE: nextcloud
   MYSQL_USER: nextcloud
   MYSQL_PASSWORD: n3x%cl0ud

 redis:
  image: redis:latest
  container_name: redis
  depends_on:
   - nginx-proxy
   - db
  restart: always
    
 nextcloud:
  image: nextcloud:latest
  container_name: nextcloud
  restart: always
  depends_on:
   - nginx-proxy
   - redis
   - db
  environment:
   - MYSQL_DATABASE=nextcloud
   - MYSQL_USER=nextcloud
   - MYSQL_PASSWORD=n3x%cl0ud
   - MYSQL_HOST=db
   - NEXTCLOUD_ADMIN_USER=admin
   - NEXTCLOUD_ADMIN_PASSWORD=admin_password
   - REDIS_HOST=redis
   - NEXTCLOUD_TRUSTED_DOMAINS=web_site
   - PHP_MEMORY_LIMIT=50G
   - PHP_UPLOAD_LIMIT=50G
   - TRUSTED_PROXIES=192.168.96.0/20
